on:
  push:
    branches:
      - master

jobs:
  compile_index_job:
    runs-on: ubuntu-latest
    name: Compile latest index.html
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
         git rebase master pages
         ./compile_index.sh > index.html
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index.html
          file_pattern: index.html
          branch: pages
