on:
  push:
    branches:
      - master

jobs:
  compile_index_job:
    runs-on: ubuntu-latest
    name: Compile latest index.html
    steps:
      - uses: actions/checkout@v2
      
      - name: Run compile script
        run: compile_index.sh

      - name: Checkout 'pages' branch
        uses: actions/checkout@v2
        with:
          ref: pages

      - name: Commit index.html to 'pages' branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "Update index.html"
          git push
